version: '3.8'

services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel_network
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: laravelpassword
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel_network

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - laravel_network

volumes:
    dbdata:

networks:
    laravel_network:
        driver: bridge
